// ─── Northstar Medical Center — Mock Data ──────────────────────────────────
// All data is fictional. No real patient information is used.

import type {
  User,
  Patient,
  Appointment,
  Visit,
  LabOrder,
  Prescription,
  Notification,
  QueueItem,
} from "./types";

// ─── Users ──────────────────────────────────────────────────────────────────

export const CURRENT_USER: User = {
  id: "usr-001",
  email: "dr.hassan@northstar.com",
  name: "Dr. Amira Hassan",
  role: "DOCTOR",
  department: "Cardiology",
  organizationId: "org-001",
};

export const ALL_USERS: User[] = [
  CURRENT_USER,
  {
    id: "usr-002",
    email: "sarah@northstar.com",
    name: "Sarah Okonkwo",
    role: "RECEPTIONIST",
    department: "Front Desk",
    organizationId: "org-001",
  },
  {
    id: "usr-003",
    email: "admin@northstar.com",
    name: "James Mwangi",
    role: "ADMIN",
    organizationId: "org-001",
  },
  {
    id: "usr-004",
    email: "pharmacist@northstar.com",
    name: "Fatima Al-Rashid",
    role: "PHARMACIST",
    department: "Pharmacy",
    organizationId: "org-001",
  },
  {
    id: "usr-005",
    email: "labtech@northstar.com",
    name: "David Chen",
    role: "LAB_TECHNICIAN",
    department: "Laboratory",
    organizationId: "org-001",
  },
  {
    id: "usr-006",
    email: "nurse@northstar.com",
    name: "Grace Njoroge",
    role: "NURSE",
    department: "General Medicine",
    organizationId: "org-001",
  },
];

// ─── Patients ───────────────────────────────────────────────────────────────

export const PATIENTS: Patient[] = [
  {
    id: "pt-001",
    medicalRecordNumber: "PT-20481",
    firstName: "Mohamed",
    lastName: "Ali",
    dateOfBirth: "1983-03-14",
    age: 43,
    sex: "male",
    phone: "+254 712 345 678",
    email: "mohamed.ali@email.com",
    address: "45 Kenyatta Avenue, Nairobi",
    emergencyContact: "Amina Ali",
    emergencyPhone: "+254 722 111 222",
    allergies: ["Penicillin"],
    bloodType: "O+",
    insuranceProvider: "NHIF",
    insuranceNumber: "NHIF-20481",
    registeredAt: "2024-01-15",
    lastVisit: "2026-08-18",
    status: "active",
    assignedDoctor: "usr-001",
  },
  {
    id: "pt-002",
    medicalRecordNumber: "PT-20482",
    firstName: "Fatuma",
    lastName: "Issa",
    dateOfBirth: "1990-07-22",
    age: 36,
    sex: "female",
    phone: "+254 733 456 789",
    address: "12 Moi Avenue, Mombasa",
    emergencyContact: "Hassan Issa",
    emergencyPhone: "+254 733 999 000",
    allergies: [],
    bloodType: "A+",
    registeredAt: "2024-03-10",
    lastVisit: "2026-08-15",
    status: "active",
  },
  {
    id: "pt-003",
    medicalRecordNumber: "PT-20483",
    firstName: "Peter",
    lastName: "Kamau",
    dateOfBirth: "1975-11-03",
    age: 50,
    sex: "male",
    phone: "+254 700 567 890",
    address: "78 Uhuru Highway, Kisumu",
    allergies: ["Aspirin", "Ibuprofen"],
    bloodType: "B-",
    insuranceProvider: "Jubilee",
    insuranceNumber: "JUB-90123",
    registeredAt: "2023-11-20",
    lastVisit: "2026-08-19",
    status: "active",
    assignedDoctor: "usr-001",
  },
  {
    id: "pt-004",
    medicalRecordNumber: "PT-20484",
    firstName: "Wanjiku",
    lastName: "Muthoni",
    dateOfBirth: "1995-05-18",
    age: 31,
    sex: "female",
    phone: "+254 711 678 901",
    email: "wanjiku.m@email.com",
    address: "23 Ngong Road, Nairobi",
    allergies: [],
    bloodType: "AB+",
    registeredAt: "2025-02-05",
    lastVisit: "2026-08-10",
    status: "active",
  },
  {
    id: "pt-005",
    medicalRecordNumber: "PT-20485",
    firstName: "Daniel",
    lastName: "Ochieng",
    dateOfBirth: "1968-01-30",
    age: 58,
    sex: "male",
    phone: "+254 722 789 012",
    address: "56 Oginga Odinga Street, Nakuru",
    emergencyContact: "Mary Ochieng",
    emergencyPhone: "+254 722 333 444",
    allergies: ["Sulfa drugs"],
    bloodType: "O-",
    insuranceProvider: "AAR",
    insuranceNumber: "AAR-45678",
    registeredAt: "2023-06-12",
    lastVisit: "2026-08-19",
    status: "active",
    assignedDoctor: "usr-001",
  },
  {
    id: "pt-006",
    medicalRecordNumber: "PT-20486",
    firstName: "Aisha",
    lastName: "Njeri",
    dateOfBirth: "2020-09-12",
    age: 5,
    sex: "female",
    phone: "+254 733 890 123",
    address: "88 Westlands Road, Nairobi",
    emergencyContact: "Kevin Njeri",
    emergencyPhone: "+254 733 555 666",
    allergies: [],
    bloodType: "A-",
    registeredAt: "2025-09-12",
    lastVisit: "2026-08-17",
    status: "active",
  },
  {
    id: "pt-007",
    medicalRecordNumber: "PT-20487",
    firstName: "Joseph",
    lastName: "Otieno",
    dateOfBirth: "1958-12-05",
    age: 67,
    sex: "male",
    phone: "+254 700 901 234",
    address: "15 Tom Mboya Street, Eldoret",
    emergencyContact: "Rose Otieno",
    emergencyPhone: "+254 700 777 888",
    allergies: ["Codeine"],
    bloodType: "O+",
    insuranceProvider: "NHIF",
    insuranceNumber: "NHIF-30891",
    registeredAt: "2022-08-30",
    lastVisit: "2026-08-19",
    status: "active",
    assignedDoctor: "usr-001",
  },
  {
    id: "pt-008",
    medicalRecordNumber: "PT-20488",
    firstName: "Lucy",
    lastName: "Wambui",
    dateOfBirth: "1988-06-25",
    age: 38,
    sex: "female",
    phone: "+254 711 012 345",
    email: "lucy.wambui@email.com",
    address: "34 Thika Road, Nairobi",
    allergies: [],
    bloodType: "B+",
    registeredAt: "2024-07-18",
    lastVisit: "2026-08-12",
    status: "active",
  },
];

// ─── Appointments ───────────────────────────────────────────────────────────

export const APPOINTMENTS: Appointment[] = [
  {
    id: "apt-001",
    patientId: "pt-001",
    patientName: "Mohamed Ali",
    doctorId: "usr-001",
    doctorName: "Dr. Amira Hassan",
    department: "Cardiology",
    date: "2026-08-19",
    time: "09:00",
    duration: 30,
    type: "consultation",
    status: "in_progress",
    reason: "Chest pain follow-up",
  },
  {
    id: "apt-002",
    patientId: "pt-003",
    patientName: "Peter Kamau",
    doctorId: "usr-001",
    doctorName: "Dr. Amira Hassan",
    department: "Cardiology",
    date: "2026-08-19",
    time: "09:30",
    duration: 30,
    type: "follow_up",
    status: "checked_in",
    reason: "Blood pressure monitoring",
  },
  {
    id: "apt-003",
    patientId: "pt-005",
    patientName: "Daniel Ochieng",
    doctorId: "usr-001",
    doctorName: "Dr. Amira Hassan",
    department: "Cardiology",
    date: "2026-08-19",
    time: "10:00",
    duration: 30,
    type: "consultation",
    status: "scheduled",
    reason: "Diabetes management review",
  },
  {
    id: "apt-004",
    patientId: "pt-002",
    patientName: "Fatuma Issa",
    doctorId: "usr-001",
    doctorName: "Dr. Amira Hassan",
    department: "Cardiology",
    date: "2026-08-19",
    time: "10:30",
    duration: 30,
    type: "consultation",
    status: "scheduled",
    reason: "Annual checkup",
  },
  {
    id: "apt-005",
    patientId: "pt-007",
    patientName: "Joseph Otieno",
    doctorId: "usr-001",
    doctorName: "Dr. Amira Hassan",
    department: "Cardiology",
    date: "2026-08-19",
    time: "11:00",
    duration: 30,
    type: "consultation",
    status: "scheduled",
    reason: "Post-surgery follow-up",
  },
  {
    id: "apt-006",
    patientId: "pt-004",
    patientName: "Wanjiku Muthoni",
    doctorId: "usr-001",
    doctorName: "Dr. Amira Hassan",
    department: "Cardiology",
    date: "2026-08-20",
    time: "09:00",
    duration: 30,
    type: "consultation",
    status: "scheduled",
    reason: "Prenatal cardiac screening",
  },
  {
    id: "apt-007",
    patientId: "pt-006",
    patientName: "Aisha Njeri",
    doctorId: "usr-001",
    doctorName: "Dr. Amira Hassan",
    department: "Cardiology",
    date: "2026-08-20",
    time: "10:00",
    duration: 20,
    type: "follow_up",
    status: "scheduled",
    reason: "Post-viral myocarditis check",
  },
];

// ─── Queue ──────────────────────────────────────────────────────────────────

export const QUEUE: QueueItem[] = [
  {
    id: "q-001",
    patientId: "pt-003",
    patientName: "Peter Kamau",
    position: 1,
    checkInTime: "08:45",
    department: "Cardiology",
    type: "appointment",
    status: "waiting",
    priority: "normal",
  },
  {
    id: "q-002",
    patientId: "pt-005",
    patientName: "Daniel Ochieng",
    position: 2,
    checkInTime: "08:50",
    department: "Cardiology",
    type: "appointment",
    status: "waiting",
    priority: "urgent",
  },
  {
    id: "q-003",
    patientId: "pt-002",
    patientName: "Fatuma Issa",
    position: 3,
    checkInTime: "08:55",
    department: "Cardiology",
    type: "appointment",
    status: "waiting",
    priority: "normal",
  },
  {
    id: "q-004",
    patientId: "pt-007",
    patientName: "Joseph Otieno",
    position: 4,
    checkInTime: "09:02",
    department: "Cardiology",
    type: "appointment",
    status: "waiting",
    priority: "normal",
  },
];

// ─── Lab Orders ─────────────────────────────────────────────────────────────

export const LAB_ORDERS: LabOrder[] = [
  {
    id: "lab-001",
    patientId: "pt-001",
    patientName: "Mohamed Ali",
    visitId: "vis-001",
    orderedBy: "usr-001",
    orderedByName: "Dr. Amira Hassan",
    testName: "Complete Blood Count",
    testType: "blood",
    status: "verified",
    requestedAt: "2026-08-18",
    result: "WBC: 7.2 (Normal)\nRBC: 4.8 (Normal)\nHemoglobin: 14.1 g/dL (Normal)\nPlatelets: 245 (Normal)",
    resultDate: "2026-08-19",
    verifiedBy: "usr-005",
  },
  {
    id: "lab-002",
    patientId: "pt-001",
    patientName: "Mohamed Ali",
    visitId: "vis-001",
    orderedBy: "usr-001",
    orderedByName: "Dr. Amira Hassan",
    testName: "Lipid Panel",
    testType: "blood",
    status: "ready",
    requestedAt: "2026-08-18",
    result: "Total Cholesterol: 242 mg/dL (HIGH)\nLDL: 162 mg/dL (HIGH)\nHDL: 38 mg/dL (LOW)\nTriglycerides: 210 mg/dL (HIGH)",
    resultDate: "2026-08-19",
  },
  {
    id: "lab-003",
    patientId: "pt-005",
    patientName: "Daniel Ochieng",
    visitId: "vis-003",
    orderedBy: "usr-001",
    orderedByName: "Dr. Amira Hassan",
    testName: "HbA1c",
    testType: "blood",
    status: "processing",
    requestedAt: "2026-08-19",
  },
  {
    id: "lab-004",
    patientId: "pt-007",
    patientName: "Joseph Otieno",
    visitId: "vis-004",
    orderedBy: "usr-001",
    orderedByName: "Dr. Amira Hassan",
    testName: "ECG",
    testType: "other",
    status: "pending",
    requestedAt: "2026-08-19",
  },
  {
    id: "lab-005",
    patientId: "pt-003",
    patientName: "Peter Kamau",
    visitId: "vis-002",
    orderedBy: "usr-001",
    orderedByName: "Dr. Amira Hassan",
    testName: "Urinalysis",
    testType: "urine",
    status: "critical",
    requestedAt: "2026-08-18",
    result: "Protein: 3+ (CRITICAL)\nGlucose: 2+ (HIGH)\nSpecific Gravity: 1.025",
    resultDate: "2026-08-19",
  },
];

// ─── Prescriptions ──────────────────────────────────────────────────────────

export const PRESCRIPTIONS: Prescription[] = [
  {
    id: "rx-001",
    patientId: "pt-001",
    patientName: "Mohamed Ali",
    visitId: "vis-001",
    doctorId: "usr-001",
    doctorName: "Dr. Amira Hassan",
    status: "pending",
    issuedAt: "2026-08-18",
    medications: [
      {
        id: "med-001",
        medicationName: "Atorvastatin 20mg",
        dosage: "20mg",
        frequency: "Once daily (evening)",
        duration: "30 days",
        quantity: 30,
      },
      {
        id: "med-002",
        medicationName: "Aspirin 81mg",
        dosage: "81mg",
        frequency: "Once daily",
        duration: "30 days",
        quantity: 30,
      },
    ],
    notes: "Take with food. Recheck lipid panel in 3 months.",
  },
  {
    id: "rx-002",
    patientId: "pt-005",
    patientName: "Daniel Ochieng",
    visitId: "vis-003",
    doctorId: "usr-001",
    doctorName: "Dr. Amira Hassan",
    status: "dispensed",
    issuedAt: "2026-08-15",
    dispensedAt: "2026-08-15",
    medications: [
      {
        id: "med-003",
        medicationName: "Metformin 500mg",
        dosage: "500mg",
        frequency: "Twice daily",
        duration: "30 days",
        quantity: 60,
        dispensed: true,
      },
      {
        id: "med-004",
        medicationName: "Gliclazide 80mg",
        dosage: "80mg",
        frequency: "Once daily (before breakfast)",
        duration: "30 days",
        quantity: 30,
        dispensed: true,
      },
    ],
  },
];

// ─── Visits ─────────────────────────────────────────────────────────────────

export const VISITS: Visit[] = [
  {
    id: "vis-001",
    patientId: "pt-001",
    appointmentId: "apt-001",
    doctorId: "usr-001",
    doctorName: "Dr. Amira Hassan",
    date: "2026-08-19",
    reason: "Chest pain follow-up",
    chiefComplaint: "Intermittent chest discomfort, especially during exertion over the past 2 weeks.",
    history: "Patient had a similar episode 6 months ago. ECG was normal at that time. Reports increased stress at work. No shortness of breath at rest.",
    vitals: {
      temperature: 36.8,
      heartRate: 78,
      bloodPressure: "142/90",
      respiratoryRate: 16,
      oxygenSaturation: 98,
      weight: 82,
      height: 175,
    },
    examination: "Heart: Regular rate and rhythm, no murmurs. Lungs: Clear bilaterally. No peripheral edema.",
    assessment: "Atypical chest pain, likely musculoskeletal. Risk factors include borderline hypertension and dyslipidemia.",
    diagnosis: ["Atypical chest pain", "Borderline hypertension", "Dyslipidemia"],
    status: "in_progress",
  },
  {
    id: "vis-002",
    patientId: "pt-003",
    doctorId: "usr-001",
    doctorName: "Dr. Amira Hassan",
    date: "2026-08-15",
    reason: "Blood pressure monitoring",
    chiefComplaint: "Routine blood pressure check.",
    vitals: {
      temperature: 36.5,
      heartRate: 72,
      bloodPressure: "158/96",
      respiratoryRate: 14,
      oxygenSaturation: 99,
    },
    diagnosis: ["Essential hypertension - uncontrolled"],
    status: "completed",
  },
  {
    id: "vis-003",
    patientId: "pt-005",
    doctorId: "usr-001",
    doctorName: "Dr. Amira Hassan",
    date: "2026-08-15",
    reason: "Diabetes management review",
    chiefComplaint: "Follow-up for Type 2 Diabetes Mellitus.",
    vitals: {
      temperature: 36.6,
      heartRate: 80,
      bloodPressure: "138/85",
      respiratoryRate: 16,
      oxygenSaturation: 97,
      weight: 91,
    },
    diagnosis: ["Type 2 Diabetes Mellitus - suboptimally controlled"],
    status: "completed",
  },
];

// ─── Notifications ──────────────────────────────────────────────────────────

export const NOTIFICATIONS: Notification[] = [
  {
    id: "notif-001",
    type: "clinical",
    title: "Lab Result Ready",
    message: "Lipid Panel results for Mohamed Ali are ready for review.",
    actionUrl: "/patients/pt-001",
    read: false,
    createdAt: "2026-08-19T08:30:00",
  },
  {
    id: "notif-002",
    type: "clinical",
    title: "Critical Lab Result",
    message: "Urinalysis for Peter Kamau shows critical protein levels.",
    actionUrl: "/patients/pt-003",
    read: false,
    createdAt: "2026-08-19T08:15:00",
  },
  {
    id: "notif-003",
    type: "operational",
    title: "Patient Checked In",
    message: "Daniel Ochieng has checked in for his 10:00 appointment.",
    read: false,
    createdAt: "2026-08-19T09:50:00",
  },
  {
    id: "notif-004",
    type: "operational",
    title: "Patient Checked In",
    message: "Fatuma Issa has checked in for her 10:30 appointment.",
    read: true,
    createdAt: "2026-08-19T10:25:00",
  },
  {
    id: "notif-005",
    type: "system",
    title: "Prescription Dispensed",
    message: "Metformin + Gliclazide for Daniel Ochieng has been dispensed.",
    read: true,
    createdAt: "2026-08-15T14:20:00",
  },
];

// ─── Helper: get patient by ID ──────────────────────────────────────────────

export function getPatient(id: string): Patient | undefined {
  return PATIENTS.find((p) => p.id === id);
}

export function getPatientFullName(patient: Patient): string {
  return `${patient.firstName} ${patient.lastName}`;
}

export function getPatientAppointments(patientId: string): Appointment[] {
  return APPOINTMENTS.filter((a) => a.patientId === patientId);
}

export function getPatientVisits(patientId: string): Visit[] {
  return VISITS.filter((v) => v.patientId === patientId);
}

export function getPatientLabOrders(patientId: string): LabOrder[] {
  return LAB_ORDERS.filter((l) => l.patientId === patientId);
}

export function getPatientPrescriptions(patientId: string): Prescription[] {
  return PRESCRIPTIONS.filter((r) => r.patientId === patientId);
}
